### ISSUE TITLE
why not completing package?

### ISSUE THREAD

**Issue by vtolstov** [google/vectorio#3]
Hi! I'm try to minimize overhead in my qemu block storage written in go and check already created packages that supports preadv/pwritev and found you package. Why you drop it?

**Comment by tedb** [comment]
Hi there, I wrote this while at Google (who owns this repo) but have since left the company and don't have access to this repo anymore.

You may be interested in Go's new support for writev, which probably makes this package deprecated: https://golang.org/pkg/net/#Buffers

**Comment by vtolstov** [comment]
Thanks, i know, but it lack of readv
